### ISSUE TITLE
How to do PWM?

### ISSUE THREAD

**Issue by jackolantern** [konsgn/MKL27_Arduino#1]
Is PWM possible?  When I call `analogWrite(pin, value)` I get the error:

```
'analogWrite' was not declared in this scope
```

Is the following sufficient?

```c
pinMode(pin, OUTPUT);
value = mapResolution(value, _writeResolution, 8);
if (value < 128) {
  digitalWrite(pin, LOW);
} else {
  digitalWrite(pin, HIGH);
}
```

are there plans to fux the commented out `analogWrite` function?  https://github.com/konsgn/MKL27_Arduino/blob/e915031d7da72cc2d7b18335c3d5c855e1c55710/cores/MKL27/wiring_analog.c#L171

**Comment by konsgn** [comment]
The commented out section is actually relevant for samd not MKL, I will implement PWM out next, and in a similar fashion, this means that only pins that have timer hardware attached to them will be able to pwm out, others will just be turned on or off.

**Comment by konsgn** [comment]
Fixed: 
Beware :
You cannot get different PWM values on pins that use conflicting resources.
